// client-vue/src/views/Login.vue
<template>
    <div class="min-h-screen bg-gray-100 flex flex-col justify-center sm:py-12">
      <div class="p-10 xs:p-0 mx-auto md:w-full md:max-w-md">
        <div class="bg-white shadow w-full rounded-lg divide-y divide-gray-200">
          <form class="px-5 py-7" @submit.prevent="login">
            <div>
              <label for="email" class="block text-sm/6 font-medium text-gray-900">Email address</label>
              <div class="mt-2">
                  <input id="email" v-model="email" type="email" autocomplete="email" required class="block w-full rounded-md border-0 px-3 py-2 mt-1 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6" />
                  <span class="text-red-500 sm:text-sm/6 block" v-for="error in errors.email">{{ error }}</span>
                </div>
            </div>
    
            <div>
              <div class="flex items-center justify-between mt-4">
                <label for="password" class="block text-sm/6 font-medium text-gray-900">Password</label>
              </div>
              <div class="mt-2">
                  <input id="password" v-model="password" type="password" autocomplete="current-password" required class="block w-full rounded-md border-0 px-3 py-2 mt-1 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6" />
                  <span class="text-red-500 sm:text-sm/6 block" v-for="error in errors.password">{{ error }}</span>
                </div>
            </div>
    
            <div>
              <button type="submit" class="flex w-full justify-center rounded-md bg-indigo-600 mt-5 px-3 py-1.5 text-sm/6 font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Sign in</button>
            </div>
          </form>
    
          <p class="py-3 text-center text-sm/6 text-gray-500">
            Not a member?
            {{ ' ' }}
            <RouterLink class="font-semibold text-indigo-600 hover:text-indigo-500" to="/register">Register</RouterLink>
          </p>
        </div>
      </div>
    </div>
</template>

<script setup>
    import { ref, reactive } from 'vue'
    import axios from 'axios'
    import { useRouter } from 'vue-router'

    const router = useRouter()

    const email = ref('')
    const password = ref('')
    const errors = ref([])

    const storeToken = (token) => {
        localStorage.setItem('authToken', token)
    }

    const login = async () => {
        try {
            const response = await axios.post('/auth/login', {
                email: email.value,
                password: password.value
            })

            storeToken(response.data.token)
            router.push('/tasks')
        } catch (error) {
          if (error.response && error.response.data.errors) {
              errors.value = error.response.data.errors
          } else {
            alert(`Error login: ${error}`)
          }
        }
    }
</script>

// client-react/src/pages/Login.jsx
import React, { useState } from 'react';
import axios from 'axios';
import { useNavigate, Link } from 'react-router-dom';

const Login = () => {
  const navigate = useNavigate();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [errors, setErrors] = useState({ email: [], password: [] });

  const storeToken = (token) => {
    localStorage.setItem('authToken', token);
  };

  const login = async (e) => {
    e.preventDefault();
    try {
      const response = await axios.post('/auth/login', {
        email,
        password,
      });

      storeToken(response.data.token);
      navigate('/tasks');
    } catch (error) {
      if (error.response && error.response.data.errors) {
        setErrors(error.response.data.errors);
      } else {
        alert(`Error logging in: ${error.message}`);
      }
    }
  };

  return (
    <div className="min-h-screen bg-gray-100 flex flex-col justify-center sm:py-12">
      <div className="p-10 xs:p-0 mx-auto md:w-full md:max-w-md">
        <div className="bg-white shadow w-full rounded-lg divide-y divide-gray-200">
          <form className="px-5 py-7" onSubmit={login}>
            <div>
              <label htmlFor="email" className="block text-sm font-medium text-gray-900">
                Email address
              </label>
              <div className="mt-2">
                <input
                  id="email"
                  type="email"
                  autoComplete="email"
                  required
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  className="block w-full rounded-md border-0 px-3 py-2 mt-1 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm"
                />
                {errors.email?.map((error, index) => (
                  <span key={index} className="text-red-500 sm:text-sm block">
                    {error}
                  </span>
                ))}
              </div>
            </div>

            <div>
              <div className="flex items-center justify-between mt-4">
                <label htmlFor="password" className="block text-sm font-medium text-gray-900">
                  Password
                </label>
              </div>
              <div className="mt-2">
                <input
                  id="password"
                  type="password"
                  autoComplete="current-password"
                  required
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="block w-full rounded-md border-0 px-3 py-2 mt-1 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm"
                />
                {errors.password?.map((error, index) => (
                  <span key={index} className="text-red-500 sm:text-sm block">
                    {error}
                  </span>
                ))}
              </div>
            </div>

            <div>
              <button
                type="submit"
                className="flex w-full justify-center rounded-md bg-indigo-600 mt-5 px-3 py-1.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
              >
                Sign in
              </button>
            </div>
          </form>

          <p className="py-3 text-center text-sm text-gray-500">
            Not a member?{' '}
            <Link className="font-semibold text-indigo-600 hover:text-indigo-500" to="/register">
              Register
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
};

export default Login;
